### Creare client
POST http://localhost:3000/clients
Content-Type: application/json

{
  "name": "Ion Popescu",
  "address": "Strada Victoriei 10, Timisoara",
  "phone_number": "0721234567"
}

### Creare comandă cu două ferestre
POST http://localhost:3000/orders
Content-Type: application/json

{
  "client_id": 1,
  "delivery_week": "2026-08-10",
  "total_amount": "85.50",
  "time_windows": [
    { "day": "thursday", "start_time": "08:00:00", "end_time": "10:00:00" },
    { "day": "thursday", "start_time": "17:00:00", "end_time": "19:00:00" }
  ]
}

### test pentru zod
POST http://localhost:3000/orders
Content-Type: application/json

{
  "client_id": 1,
  "delivery_week": "10-08-2026",
  "total_amount": "abc",
  "time_windows": []
}

### tranzactie invalida
PATCH http://localhost:3000/stops/1
Content-Type: application/json

{
  "status": "delivered",
  "paid_cash": "50.00",
  "paid_transfer": "35.50"
}

### asignare zi
PATCH http://localhost:3000/orders/1/day
Content-Type: application/json

{ "day": "thursday" }

### livrare
PATCH http://localhost:3000/stops/1
Content-Type: application/json

{
  "status": "delivered",
  "paid_cash": "50.00",
  "paid_transfer": "35.50"
}
###
GET http://localhost:3000/orders?week=2026-08-10